services:
  web:
    container_name: sigint-api-server
    build: .
    ports:
      - "8000:8000"
    env_file:
      - ".env"
    volumes:
      - ./:/usr/src/app
      # some cheap trickery to bring the common module into scope
      - ../common:/usr/src/app/common
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sigint-api.tls=true"
      - "traefik.http.routers.sigint-api.rule=Host(`${FQDN}`)"
      - "traefik.http.routers.sigint-api.entrypoints=websecure"
      - "traefik.http.routers.sigint-api.service=sigint-api"
      - "traefik.http.services.sigint-api.loadbalancer.server.port=8000"
      - "traefik.http.routers.sigint-api.tls.certResolver=letsEncryptResolver"

    restart: unless-stopped
    networks:
      - traefik_public
      - database

networks:
  traefik_public:
    external: true
  database:
    external: true
